Group: Default
DisplayName: "&7默认组&r"
Prefix: "&7[Default] &r"
Suffix: none
Format:
  Join: "&7[&a+&7] %player_display%"
  Quit: "&7[&c-&7] %player_display%"
  Chat: "<%display%> %message%"
Hide: false
Permissions:
  - "functions.default.*"
atPlayer: "&2@%player%&r"
